name: Build CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qt6-base-dev libqt6svg6-dev libmpv-dev libsqlite3-dev libmecab-dev mecab-ipadic libjson-c-dev libzip-dev mesa-common-dev python3-dev

    - name: CMake Build
      run: |
        mkdir build
        cd build
        cmake .. -DOCR_SUPPORT=ON -DMEMENTO_COMPILER_FLAGS=-Werror
        cmake --build . -j $(nproc)

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-qt6
          mingw-w64-x86_64-mpv
          mingw-w64-x86_64-mecab
          mingw-w64-x86_64-json-c
          mingw-w64-x86_64-libzip
          mingw-w64-x86_64-python

    - uses: actions/checkout@v4

    - name: CMake Build
      run: |
        mkdir build
        cd build
        cmake .. -DOCR_SUPPORT=ON -DMEMENTO_COMPILER_FLAGS=-Werror
        cmake --build . -j $(nproc)

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update || true
        brew install cmake sqlite3 qt6 mpv mecab mecab-ipadic json-c libzip python || true

    - name: CMake Build
      run: |
        mkdir build
        cd build
        cmake .. -DOCR_SUPPORT=ON -DMEMENTO_COMPILER_FLAGS=-Werror
        cmake --build . -j $(nproc)
